version: "2"
services:
  mongo:
    image: mongo:3.6
    volumes:
      - database:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:4.0
    ports:
      - 6379:6379

  bluquist:
    build:
      context: "."
    env_file: ./config.env
    depends_on:
      - mongo
      - redis
    ports:
      - 80:80

volumes:
  database:
    driver: local